Repository sunset-wasteland/sunset-wasteland, pull requests merged in 2022-11, with the labels that each got.

#680 Bighorn Power Plant (Properly, this time)
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/modules/fallout/areas/area.dm
  code/modules/jobs/job_types/bighorn.dm
  code/modules/jobs/job_types/followers.dm
Labels: Quality of Life, DO NOT MERGE, Needs Author Attention

#716 Stealth nanites, now with stealth
  code/datums/components/nanites.dm
  code/modules/research/nanites/nanite_programs/utility.dm
Labels: DO NOT MERGE, Balance

#702 Follower Guard Overhaul
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/followers.dm
  code/modules/jobs/jobs.dm
Labels: DO NOT MERGE, Balance, Needs Author Attention
