Repository sunset-wasteland/sunset-wasteland, pull requests merged in 2022-06, with the labels that each got.

#99 Various Map Improvements
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/game/machinery/firealarm.dm
  code/modules/arousal/genitals_sprite_accessories.dm
  code/modules/client/preferences.dm
  sound/machines/siren.ogg
Labels: Map, Code, Quality of Life, Needs Testing

#109 Bighorn Expanded and Enhanced™ First Edition
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  modular_sunset/code/game/objects/sunsetmisc.dm
  modular_sunset/icons/structures/sunset_signs.dmi
Labels: Map, Sprites, Quality of Life

#123 Fix for Khan ranks showing as 'NOPE'
  code/datums/datacore.dm
  code/modules/jobs/job_types/khan.dm
Labels: bugfix

#120 Medicine rebalance, survival mode edition.
  code/modules/fallout/reagents/medicines.dm
Labels: Balance

#133 More Emotes for the Emote Bloat - Wet Your Whistle Edition
  code/modules/mob/living/emote.dm
  sound/f13effects/sunsetsounds/bark.ogg
  sound/f13effects/sunsetsounds/birdkyaa.ogg
  sound/f13effects/sunsetsounds/blush.ogg
  sound/f13effects/sunsetsounds/bork.ogg
  sound/f13effects/sunsetsounds/choke.ogg
  sound/f13effects/sunsetsounds/cougar.ogg
  sound/f13effects/sunsetsounds/dog-miserable.ogg
  sound/f13effects/sunsetsounds/femalechuckle.ogg
  sound/f13effects/sunsetsounds/fenbark.ogg
  sound/f13effects/sunsetsounds/foxbark.ogg
  sound/f13effects/sunsetsounds/lilburp.ogg
  sound/f13effects/sunsetsounds/lynx.ogg
  sound/f13effects/sunsetsounds/malechuckle.ogg
  sound/f13effects/sunsetsounds/panda.ogg
  sound/f13effects/sunsetsounds/rabbit.ogg
  sound/f13effects/sunsetsounds/trumpet.ogg
  sound/f13effects/sunsetsounds/whistle-overhere.ogg
  sound/f13effects/sunsetsounds/wolfhowl.ogg
  sound/f13effects/sunsetsounds/yap.ogg
Labels: Quality of Life

#151 Allows crude militaristic outfits (AKA GWTB-inspired) coats and helmets to be reinforced
  modular_sunset/code/modules/clothing/head/f13head.dm
  modular_sunset/code/modules/clothing/suits/f13suits.dm
Labels: Quality of Life

#159 Customisation Update
  _maps/map_files/Pahrump-Sunset/Warren.dmm
  code/game/objects/items/documents.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/structures/signs/signs_plaques.dm
  code/modules/fallout/obj/stack/f13Cash.dm
  code/modules/fallout/obj/structures/obstacle.dm
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/paperwork/stamps.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  icons/fallout/objects/guns/ballistic.dmi
  icons/fallout/turfs/smoothing.dmi
  icons/mob/human_parts.dmi
  icons/mob/wings.dmi
  icons/obj/decals.dmi
  icons/obj/decalslong.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/icons/mob/mam_ears.dmi
  modular_citadel/icons/mob/mam_tails.dmi
Labels: Code, Sprites, Quality of Life, DO NOT MERGE

#171 convert centcomm.dmm to tgm format
  _maps/map_files/generic/CentCom.dmm
Labels: Map, bugfix

#170 Fixed curtains to have no density
  code/game/objects/structures/watercloset.dm
Labels: bugfix

#179 Nerfs to FEV Ghouls
  code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
Labels: Balance

#180 Khan fortress upgrade & tweaks
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  _maps/map_files/Pahrump-Sunset/Warren.dmm
  fortune13.dme
  modular_sunset/code/game/objects/sunset_posters.dm
  modular_sunset/code/game/objects/sunsetmisc.dm
  modular_sunset/icons/structures/sunset_grafitti.dmi
  modular_sunset/icons/structures/sunset_posters.dmi
  modular_sunset/icons/structures/sunset_signs_res.dmi
  modular_sunset/icons/structures/sunset_signs_small.dmi
Labels: Map, Code, Quality of Life
