Repository sunset-wasteland/sunset-wasteland, pull requests merged in 2022-10, with the labels that each got.

#534 ASSHOLE NCR BIAS CODER DRAGONFRUITS BUFFS HIS FAVORITE FACTION AGAIN (FALLOUT 13 IS !RUINED!)
  code/modules/jobs/job_types/ncr.dm
Labels: Code, Balance

#594 DNA Vault update
  code/modules/station_goals/dna_vault.dm
Labels: DO NOT MERGE, Needs Author Attention

#629 Cargos misc crates + diagnostic hud removal
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  _maps/shuttles/cargo_pahrump.dmm
  code/game/objects/items/sharpener.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/goodies.dm
  code/modules/cargo/packs/organic.dm
  code/modules/cargo/packs/security.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/techweb/nodes/computer_hud_nodes.dm
Labels: DO NOT MERGE, Balance, Needs Author Attention

#660 Xenobio fix/nerf
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
  code/modules/research/xenobiology/crossbreeding/stabilized.dm
Labels: DO NOT MERGE, Balance, Needs Author Attention

#667 Sanitize most string interpolations in queries
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/create_poll.dm
  code/modules/admin/ipintel.dm
  code/modules/library/lib_machines.dm
  code/modules/mob/dead/new_player/poll.dm
  code/modules/shuttle/emergency.dm
Labels: Priority - High

#670 Enclave camera problems
  _maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
Labels: DO NOT MERGE, Needs Author Attention
